id: template_chat_flow
name: Template Chat Flow
environment:
  python_requirements_txt: requirements.txt
environment_variables:
  PF_DISABLE_TRACING: true
inputs:
  chat_history:
    type: list
    default: []
    is_chat_input: false
    is_chat_history: true
  query:
    type: string
    default: Are there areas that are wheelchair accessible?
    is_chat_input: true
outputs:
  reply:
    type: string
    reference: ${generateReply.output}
    is_chat_output: true
  documents:
    type: string
    reference: ${selectChunks.output}
nodes:
- name: formatRewriteIntentInputs
  type: python
  source:
    type: code
    path: formatConversationForIntentRewriting.py
  inputs:
    history: ${inputs.chat_history}
    max_tokens: 2000
    query: ${inputs.query}
  use_variants: false
- name: rewriteIntent
  type: llm
  source:
    type: code
    path: ragcore/prompt_templates/rewriteIntent.jinja2
  inputs:
    deployment_name: gpt-4o-mini
    temperature: 0.7
    top_p: 0.95
    max_tokens: 120
    presence_penalty: 0
    frequency_penalty: 0
    conversation: ${formatRewriteIntentInputs.output}
  connection: azure_open_ai
  api: chat
  use_variants: false
- name: extractSearchIntent
  type: python
  source:
    type: code
    path: extractSearchIntent.py
  inputs:
    intent: ${rewriteIntent.output}
  use_variants: false
- name: querySearchResource
  type: python
  source:
    type: package
    tool: promptflow_vectordb.tool.common_index_lookup.search
  inputs:
    mlindex_content: >
      embeddings:
        api_base: https://cjam3-azaipoc-ai-ais.openai.azure.com
        api_type: azure_ad
        api_version: 2023-07-01-preview
        batch_size: '16'
        connection:
          id: >-
            /subscriptions/dd32f726-d09b-4093-add0-56d8cbdb4ed0/resourceGroups/cjam3-azaipoc-ai-rg/providers/Microsoft.MachineLearningServices/workspaces/cjam3-azaipoc-ai-aip-001/connections/cjam3-azaipoc_aoai
        connection_type: workspace_connection
        deployment: text-embedding-ada-002
        dimension: 1536
        file_format_version: '2'
        kind: open_ai
        model: text-embedding-ada-002
        schema_version: '2'
      index:
        api_version: 2024-05-01-preview
        connection:
          id: >-
            /subscriptions/dd32f726-d09b-4093-add0-56d8cbdb4ed0/resourceGroups/cjam3-azaipoc-ai-rg/providers/Microsoft.MachineLearningServices/workspaces/cjam3-azaipoc-ai-aip-001/connections/cjam3-azaipoc-ai-srch
        connection_type: workspace_connection
        endpoint: https://cjam3-azaipoc-ai-srch.search.windows.net
        engine: azure-sdk
        field_mapping:
          content: content
          embedding: contentVector
          filename: filepath
          metadata: meta_json_string
          title: title
          url: url
        index: grand-canyon-tours
        kind: acs
        semantic_configuration_name: azureml-default
    queries: ${extractSearchIntent.output}
    query_type: Hybrid (vector + keyword)
    top_k: 5
  use_variants: false
- name: chunkDocuments
  type: python
  source:
    type: code
    path: chunkDocuments.py
  inputs:
    data_source: Azure AI Search
    max_tokens: 1050
    queries: ${extractSearchIntent.output}
    query_type: Hybrid (vector + keyword)
    results: ${querySearchResource.output}
    top_k: 5
  use_variants: false
- name: selectChunks
  type: python
  source:
    type: code
    path: filterChunks.py
  inputs:
    min_score: 0.3
    results: ${chunkDocuments.output}
    top_k: 5
  use_variants: false
- name: shouldGenerateReply
  type: python
  source:
    type: code
    path: shouldGenerateReply.py
  inputs:
    chunks: ${selectChunks.output}
    queries: ${extractSearchIntent.output}
  use_variants: false
- name: formatGenerateReplyInputs
  type: python
  source:
    type: code
    path: formatReplyInputs.py
  inputs:
    chunks: ${selectChunks.output}
    history: ${inputs.chat_history}
    max_conversation_tokens: 2000
    max_tokens: 5000
    query: ${inputs.query}
  use_variants: false
- name: generateReply
  type: llm
  source:
    type: code
    path: ragcore/prompt_templates/generateReply.jinja2
  inputs:
    inputs: ${formatGenerateReplyInputs.output}
    deployment_name: gpt-4o-mini
    temperature: 0.7
    top_p: 0.95
    max_tokens: 800
    presence_penalty: 0
    frequency_penalty: 0
    indomain: "True"
    role_info: >-
      You are a travel advisor that assists travelers in planning their trip to
      the Grand Canyon. Use the indexed travel brochures to answer customer
      questions. Supplement your responses with internal knowledge only to
      provide clarity or context, but ensure all answers strictly align with the
      information from the indexed Grand Canyon brochures.


      # Instructions


      - Base all responses on the content found in the indexed travel brochures for the Grand Canyon.

      - Use internal knowledge only to provide clarity or context, such as defining terms or enhancing understandability, but do not fabricate details beyond what is in the brochures.

      - If the question covers a topic not found in the travel brochures, politely inform the traveler that the brochures do not include that information.

      - Ensure your tone remains professional, welcoming, and informative throughout the interaction.


      # Output Format


      Responses should be concise, accurate, and informed by the brochures. Use complete sentences and structure information logically for ease of understanding. 


      # Examples


      ### Example 1

      **Traveler's Question:** What are the best times to visit the Grand Canyon?


      **Response:** According to the indexed travel brochures, the best times to visit the Grand Canyon are spring (March to May) and fall (September to November) due to the milder temperatures and fewer crowds. These seasons provide ideal conditions for hiking and other outdoor activities. 


      ### Example 2

      **Traveler's Question:** Can I camp inside the Grand Canyon?


      **Response:** The brochures indicate that camping is allowed inside the Grand Canyon at designated campgrounds, such as the Bright Angel Campground near Phantom Ranch. Permits are required for overnight camping below the rim, and reservations should be made well in advance due to high demand.


      ---


      For questions not explicitly covered in the brochures, include the following response:  

      *"This specific information is not included in the available Grand Canyon travel brochures. Is there something else I can help you with?"*  


      # Notes


      - Ensure responses reflect only the information contained within the Grand Canyon brochures. Do not incorporate external knowledge or speculations unless explicitly called out for clarity.  

      - If a question pertains to multiple aspects (e.g., weather, activities, accommodations), address each aspect separately for greater clarity.
  connection: azure_open_ai
  api: chat
  activate:
    when: ${shouldGenerateReply.output}
    is: true
  use_variants: false
